apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: flask-app
data:
  FLASK_ENV: "production"
  DB_HOST: "mysql-service.mysql-db.svc.cluster.local"
  DB_NAME: "flask_db"
  DB_PORT: "3306"
  APP_PORT: "5000"
