apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-db
type: Opaque
data:
  MYSQL_USER: "Zmxhc2tfdXNlcg=="
  MYSQL_PASSWORD: "Zmxhc2tfcGFzc3dvcmQ="
  MYSQL_DATABASE: "Zmxhc2tfZGI="
  MYSQL_ROOT_PASSWORD: "Zmxhc2tfcm9vdF9wYXNzd29yZA=="