FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 9090

# CMD ["gunicorn", "--workers", "4", "--threads", "2", "-b", "0.0.0.0:9090", "app:app"]
# Explicitly use the working directory context to call gunicorn
CMD ["gunicorn", "--workers=4", "--threads=2", "--bind=0.0.0.0:9090", "app:app"]